language: python
python:
    - "2.7"
env:
    - cyclone
install:
    - "pip install -r requirements.txt --use-mirrors"
    - "pip install https://github.com/vltr/cyclone/archive/master.zip"
    - "pip install pytest"
    - "pip install pytest-cov"
    - "pip install coverage"
    - "pip install coveralls"
    - "pip install mock"
script:
    coverage run --source=shissen setup.py test
after_success:
    coveralls --verbose
